---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mobiliar/repositories/app-sintia  # Ruta donde se despliega tu aplicación
    - cd $DEPLOYPATH  pull origin prueba  # Realiza el pull en la rama main
